### ISSUE TITLE
Question about MATH prompt and evaluation metrics

### ISSUE THREAD

**Issue by veronica320** [iiis-ai/cumulative-reasoning#1]
Hi authors, 

Thanks for your excellent work! May I ask a few questions about your experiments on the MATH dataset?

1. Which parts in your [prompt](https://github.com/iiis-ai/cumulative-reasoning/blob/6c8632577699a8b3f8eee88671ee83c677fa4aea/MATH/math-cr-4shot.py#L117) correspond to the Proposer, Verifier, and Reporter, respectively? It looks like the hints, intermediate questions and answers, and final answer are all parts of "proposing", but I fail to find anything about "verifying and "reporting". Did I miss anything?

2. Is the evaluation also done by GPT4, according to [this function](https://github.com/iiis-ai/cumulative-reasoning/blob/6c8632577699a8b3f8eee88671ee83c677fa4aea/MATH/math-cr-4shot.py#L308)? How well does it correlate with oracle judgements?

Thanks in advance for any input!

**Comment by yifanzhang-pro** [comment]
Hello,

Thank you for taking the time to read our paper and for your thoughtful questions regarding the experiments on the MATH dataset. We appreciate the interest in the roles of the Proposer, Verifier, and Reporter within the Cumulative Reasoning (CR) framework. Below, I'll address each of your points.

### Response to Question 1

#### On the Roles of Proposer, Verifier, and Reporter in Our Experiments

1. **Role of Proposer**: You are correct in noting that the hints, intermediate questions, and answers could all be viewed as parts of "proposing." In our implementation, the Proposer initiates the reasoning process by suggesting the next steps or claims based on the existing context. This is indeed a sophisticated mechanism that employs problem decomposition strategies.

2. **Role of Verifier**: In the current iteration of our work, we opted not to implement the Verifier models. This decision was primarily driven by the computational and financial constraints associated with running extensive experiments, the inclusion of verifiers could substantially increase the computational cost. Therefore, we have decided to leave the exploration of this dimension for future work.

3. **Role of Reporter**: In the absence of a Verifier, the last step within the reasoning process essentially acts as a Reporter, concluding the chain of thought and delivering the final answer. This design was chosen for its flexibility and its ability to save tokens, thus making the reasoning process more efficient.

#### Flexibility of Cumulative Reasoning (CR)

The CR framework was designed to be highly flexible. In its most stripped-down form, without verifiers, CR can be seen as an enhanced Chain of Thought (CoT) model that employs sophisticated problem decomposition strategies. The Reporter in this case is implicitly the last step in the reasoning process, which serves to deliver the final answer.

#### Financial and Computational Constraints

We acknowledge that the absence of a Verifier model could be viewed as a limitation. However, it's crucial to consider the computational and financial resources required for such an endeavor. Including Verifier models for every iteration could result in an exponential increase in computational cost, potentially running into tens of thousands of dollars for the experiments.

#### Future Work and Fair Comparison

We recognize the allure of using symbolic verifiers like Sympy, Mathematica, or Lean to bring an additional layer of rigor to our approach. However, integrating such tools would make direct comparisons to current state-of-the-art results less straightforward. This is an intriguing avenue that we are keen to explore in future work.

Once again, thank you for your thoughtful questions. They touch on important facets of our work, and we appreciate the opportunity to clarify these points. We hope this response provides a comprehensive answer to your queries. Please don't hesitate to reach out with further questions or comments.


### Response to Question 2

Thank you for your additional question on the evaluation methodology we used in our paper, particularly with respect to the role of GPT-4 in judging the correctness of the answers. This is an excellent question that speaks to the integrity of the experimental process. Allow me to clarify.

#### Role of the Evaluator in Our Experiments

1. **Ground Truth Comparison and Format Leniency**: In the evaluation phase, the evaluative model—GPT-4 in our specific implementation—receives the ground truth answer for cross-verification purposes. This model serves a pivotal role as the arbiter of answer correctness, ensuring that the output generated through our Cumulative Reasoning (CR) algorithm aligns accurately with the established truth. While the evaluator has been designed to afford some latitude in answer formatting, it adheres to a stringent criterion when assessing the substance of the answer. 

    - **Example Scenario**: To elaborate, consider a situation where the final answer generated by CR is \( (3, \frac{\pi}{2}) \), and the ground truth corroborates this as \( (3,\frac{\pi}{2}) \). Despite inconsequential formatting discrepancies—such as the absence or presence of spaces around the comma—the evaluator recognizes these answers as equivalent in content, thereby validating their correctness.

    - **Multiple Choice Evaluation**: In cases where the problem format is that of multiple choices, say options (A), (B), and (C), the evaluator is sufficiently flexible to accept either the label of the correct choice or its content as a valid answer. This ensures that we capture the essence of correctness irrespective of the answer's representational form.

   **Log Files**: For transparency and traceability, you can check the log files to understand how the evaluator is operating during the evaluation process.

#### Reproducibility and Correlation with Oracle Judgements (Manually Evaluated)

2. **Alignment with Previous SOTA Methods**: One of the key considerations during the evaluation was to ensure that our results were comparable with previous state-of-the-art methods. To this end, we have replicated the results of Complex-CoT and Complex-CoT with progressive-hint prompting using the same evaluation methodology. The overall accuracy rates are quite close to the reported results in the literature.

    - **Reported by Previous Research**: Complex-CoT: 50.36%; Complex-CoT (w/ progressive-hint prompting): 53.90%.
    - **Our Reproduced Results**: Complex-CoT*: 48.80%; Complex-CoT (w/ progressive-hint prompting)*: 53.80%.

    These closely matching results underscore the reliability of our evaluation process and lend credence to the performance gains we reported using Cumulative Reasoning (CR).

Thank you for bringing up this important point. A robust evaluation methodology is crucial for validating any new approach, and your question provides an excellent opportunity to clarify the details of our evaluation process. We hope this comprehensive response addresses your inquiry adequately. Should you have further questions or need additional clarification, please feel free to ask.

Best regards,

**Comment by veronica320** [comment]
Thanks for your detailed response! I appreciate that. Would you mind reopening the issue for a few follow-ups?

1. Would it be possible to also clarify these two facts (that you didn't implement the Verifier and the Reporter, and that you used GPT-4 for evaluation) in your paper? Currently there's no mention of them, which has been somewhat misleading.
A reader would assume that all modules are implemented as described in the Method section, and that "accuracy" is accuracy evaluated by oracle.

2.  The last subtitle in your reply mentioned "Correlation with Oracle Judgements", but I didn't find the relevant elaboration in that paragraph. Did I miss something?

**Comment by yjqqqaq** [comment]
Thank you for your suggestions. 
We will clarify the implementation of CR in MATH tasks in the next version of our paper. In addition, we manually reviewed the given results of CR (w/ PHP), and found that GPT-4 almost made no judgement errors. The only error was the misjudgment of 3^5 being equal to 81, and this error did not occur in other repeated experiments. If you find other judgement errors in our experimental results, please feel free to contact us.  We will mention in the next version of our paper that we used GPT-4 as the judger, and elaborate on the feasibility of GPT-4 as a judger.
Best regards.

**Comment by veronica320** [comment]
Thank you for your reply! I appreciate that.
