### ISSUE TITLE
About pip env 'guidance==0.0.64 for openai' 

### ISSUE THREAD

**Issue by Hanochhu** [iiis-ai/cumulative-reasoning#2]
<img width="1034" alt="image" src="https://github.com/iiis-ai/cumulative-reasoning/assets/52187558/5c3892b9-447b-4087-af2b-aef9ed1bfab1">
as the picture shows ,"guidance==0.0.64 for openai"can't be found.

**Comment by yifanzhang-pro** [comment]
Well, you just need to delete `for openai`, that is: `pip install guidance==0.0.64`

**Comment by Hanochhu** [comment]
ok
