### ISSUE TITLE
code for the best result on the leaderboard of the MATH dataset for the paper with code.  I mean the CR agent(GPT-4 model, with code)

### ISSUE THREAD

**Issue by runzeer** [iiis-ai/cumulative-reasoning#4]

**Comment by yifanzhang-pro** [comment]
Please see `/CR-Agent` folder for the output log and prompts on the MATH dataset, we will update the code soon (based on ToRA).

**Comment by runzeer** [comment]
> Please see `/CR-Agent` folder for the output log and prompts on the MATH dataset, we will update the code soon (based on ToRA).

Thanks a lot for your kindly reply. So What is the exact time then? I can hardly wait.

**Comment by yifanzhang-pro** [comment]
Released CR Agent v0.1 and CR Agent Assistant v0.1.
