### ISSUE TITLE
Issue about Guidance Select

### ISSUE THREAD

**Issue by shenz2-2000** [iiis-ai/cumulative-reasoning#5]
Hello, 

Thank you for your great work! 

When running the code for Game of 24, I encounter the following error, which seems to be caused by the openai api update:

![issue](https://github.com/iiis-ai/cumulative-reasoning/assets/61441331/e63726d8-c436-42e5-8c0c-53e05c598a28)

May I ask how to solve this issue? 

I am using openai version 0.28.1, thanks for your suggestions in advance.

**Comment by yjqqqaq** [comment]
Thank you for your attention to our project. The main cause of this issue is indeed as you mentioned, due to the update of OpenAI's API. We have found that the current version of Guidance (0.0.64 used by CR) is not compatible with OpenAI models after 1106 (like gpt-4-1106-preview). However, 0613 and earlier models (like gpt-4-0613) are supported well. Hope that it resolves your issue.

**Comment by yjqqqaq** [comment]
Also, you can try to migrate to closer Guidance (version > 0.1). We will also update the eval scripts in the future.

**Comment by shenz2-2000** [comment]
> Thank you for your attention to our project. The main cause of this issue is indeed as you mentioned, due to the update of OpenAI's API. We have found that the current version of Guidance (0.0.64 used by CR) is not compatible with OpenAI models after 1106 (like gpt-4-1106-preview). However, 0613 and earlier models (like gpt-4-0613) are supported well. Hope that it resolves your issue. 

Thanks for your suggestion. Unfortunately, I found that gpt-4-0613 also does not work either, and this cannot be resolved by changing the version of OpenAI or guidance package. I would greatly appreciate it if you could update the repo soon to make it compatible with the current version of OpenAI. l will also try to see whether I can migrate it to guidance 0.1 version.

Again thank you for the great work!

**Comment by yifanzhang-pro** [comment]
We have implemented the CR Agent using pure Meta Prompting to let the AI Agent directly write a Python program to solve the Game of 24 tasks,  and **process all samples in one response, n time faster than previous methods**.  Please see https://github.com/meta-prompting/meta-prompting for details (CR-Agent-XML v0.2 Success Rate: 100%, Time usage: 0.08s per sample)
